### PR TITLE
Updated proto

### PR DESCRIPTION
**Pull request by cheesynoob**

### CODE REVIEW

**Comment by thelostcode** [comment]
Approve this. +1

**Comment by MaxLeiter** [comment]
Can we avoid using multi line comments for consistency?

**Comment by cheesynoob** [comment]
Removed the multi-line comment

**Comment by MaxLeiter** [comment]
Squash and then good to go

**Comment by cheesynoob** [comment]
Got conflicted and it was easier to just make a new one

**Pull request closed without merging**
