### PR TITLE
Dump encrypted messages to disk too

### PR DESCRIPTION
**Pull request by ur0**
Also uses the last device in DeviceManager (should work for about everyone, better than coding a static device ID).

### CODE REVIEW

**Comment by ur0** [comment]
I'm also wondering if I should dump to a path outside the `scripts` directory.

**Comment by nullpixel1** [comment]
Hi: one suggestion. Can you make it a CLI and let it take a device ID argument, and then I'll merge it.

👍

**Comment by ur0** [comment]
@nullpixel1 sure. I'm tracking you guys on Discord, so just highlight me and I'll respond (I'm @ur0 there too).

**Comment by Mandrakia** [comment]
Device ID was ok for most dev as we have VM's android and stuff. It was the only way to be sure to attach the the real device.

**Comment by ur0** [comment]
@Mandrakia it's a positional arg now.

**Comment by nullpixel1** [comment]
I'm lovin' it.

**Comment by TalSkverer** [comment]
@ur0 great change, thank you!

**Pull request merged**
