### PR TITLE
Possible App Version...

### PR DESCRIPTION
**Pull request by ElGorditoSabrosito**
Just matching proto with Apple Store Version.

https://itunes.apple.com/es/app/pokemon-go/id1094591345?mt=8

I don't have technical background to support this only guessing.

### CODE REVIEW

**Comment by SpencerSharkey** [comment]
good guess

**Comment by xssc** [comment]
Need someone to test this first, an old IPA would be helpful

**Comment by LoungeKatt** [comment]
1.0.2 / 0.29.2 - https://ufile.io/cb470 (Core binary only)

It will probably take me longer to set up a virtual machine to run IDA (Mac) than it will leaving this here.

**Comment by TalSkverer** [comment]
My Android emulator sends Unk9 message as well, so that's might not be the version of iOS...

**Comment by wchill** [comment]
This has been determined to be incorrect; it's not the iOS version number.

**Pull request closed without merging**
