### PR TITLE
SensorInfo Variable Renaming

### PR DESCRIPTION
**Pull request by gnought**
Is it make sense?

### CODE REVIEW

**Comment by MaxLeiter** [comment]
I'm going to hold off on merging this until we can verify these are correct.

@pkmngodev/reverseengineers would appreciate your thoughts

**Comment by firebolt55439** [comment]
FYI, for `accel_z`, 9.8 is not a random number - it is the acceleration due to Earth's gravity (9.8 m/s^2) and an important constant in physics.

**Comment by cyraxx** [comment]
@firebolt55439 Yeah that's how we figured out that those were acceleration values :wink:

@MaxLeiter I think this is fine to merge. However due to recent .proto fixes it now has conflicts - can you update your branch @gnought?

**Comment by nullpixel1** [comment]
Please can you rebase your commit

**Comment by gnought** [comment]
I have accidentally delete my branch, sorry for that. I create a new PR.

**Pull request closed without merging**
