### PR TITLE
refactored sub_8930C

### PR DESCRIPTION
**Pull request by cpainchaud**
great chances to be a decrypt/encrypt function as it's a 1:1 destructive function

### CODE REVIEW

**Comment by MaxLeiter** [comment]
Please rebase and squash

**Comment by MaxLeiter** [comment]
Why was this closed?

**Comment by cpainchaud** [comment]
sorry , got issues with conflicts ... prefered to send a new one, all clean

**Comment by cpainchaud** [comment]
btw what did you mean by "rebase and squash" ?

**Comment by MaxLeiter** [comment]
I'm on mobile and can't be of much help; rebasing would mean updating to master, basically, and squashing would merge all your commits into one. Google can help better then me, and if you need more help feel free to ask on slack.

**Comment by Stunner** [comment]
https://www.atlassian.com/git/tutorials/merging-vs-rebasing/conceptual-overview Scroll down to "Interactive Rebasing". You have a lot of commits here, especially considering your fix of typos as separate commits. What he wants you to do is rewrite the git history so that all your changes are combined into fewer commits. It'll be easier for others who look back through the history that way (once your changes are merged in).

**Comment by cpainchaud** [comment]
interesting, thx !

**Pull request closed without merging**
