### PR TITLE
Remove incorrect decrypt implementation

### PR DESCRIPTION
**Pull request by globeriz**
removed decrypt funcs only

### CODE REVIEW

**Comment by rryles** [comment]
Looks good to me.  I don't see the point in decrypting anyway.

**Comment by trisk** [comment]
Please change the commit title to something like "Remove incorrect decrypt implementation"

**Comment by nullpixel1** [comment]
Changed @trisk

**Comment by trisk** [comment]
Good to push.

**Comment by Abraxas000** [comment]
The whole "Encrypt/Decrypt" terminology is incorrect anyways (probably confuses new devs). What we're doing is creating a hash which is damn near impossible to reverse the algorithms for; especially in this case with so many convoluted computations in the mix. Niantic clearly spent a LOT of time working out numerous hashing methods that are difficult/impossible to reverse.

Regardless, I'm still looking into whether or not I can reverse it mathematically xD

**Comment by Abraxas000** [comment]
Nope, not remotely possible to "decrypt".

**Pull request merged**
