### PR TITLE
Update encrypt.c

### PR DESCRIPTION
**Pull request by globeriz**
removed the decrypt function that doesn't work

### CODE REVIEW

**Comment by MaxLeiter** [comment]
I'd like @wchill to sign off on this.

**Comment by rryles** [comment]
The encrypt() function has also gone!?

**Comment by keyphact** [comment]
I would also like @wchill to give this a once over before committing. Unless most of us agree it's good to go @pkmngodev/reverseengineers ?

**Comment by globeriz** [comment]
this is based on 1 commit backwards in private repo

**Comment by Abraxas000** [comment]
This PR also currently removes the encrypt function.

**Pull request closed without merging**
